kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kstatus-watch
  labels:
    origin: flux
    owner: kstatus
subjects:
- kind: ServiceAccount
  name: kstatus
  namespace: status
roleRef:
  kind: ClusterRole
  name: kstatus-watch
  apiGroup: rbac.authorization.k8s.io
  