kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kstatus-watch
  labels:
    origin: flux
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
  