apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: myautomation
  namespace: demo
  labels:
    origin: flux
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.workload: glob:test-*
    flux.weave.works/tag.opa: semver:~1.0
spec:
  releaseName: aut01
  chart:
    git: git@github.com:ipedrazas/flux-tutorial.git
    ref: master
    path: charts/automation
  values:
    image.repository: ipedrazas/automation
    image.tag: test-v1